# 18/04 - Pair Programming Numpy 1 - Tatiana & Lara

In [1]:
import numpy as np

# Ejercicio 1 


Crear 3 arrays. 1) dos dimensiones, 2 filas y 3 col; 2) 3 dim, 2 matrices,3 filas, 5 col. *) 

In [2]:
#Array 1

lista1 = [1, 2, 3, 4, 5]
array_1 =np.array(lista1)
array_1

array([1, 2, 3, 4, 5])

In [4]:
#Array 2 (dos dimensiones, 2 filas, 3 col)

array_2 = np.random.randint (1, 10, (2, 3))
array_2

array([[6, 9, 8],
       [3, 5, 2]])

In [5]:
#Array 3 (2 matrices, 3 filas, 5 col)

array_3 = np.random.rand(2, 3, 5)
array_3

array([[[0.60273906, 0.89757772, 0.9521491 , 0.85145229, 0.75894662],
        [0.91379953, 0.33584673, 0.93162511, 0.72580759, 0.6654558 ],
        [0.32334015, 0.89370783, 0.89043428, 0.41404964, 0.27351203]],

       [[0.72896408, 0.35047846, 0.7696711 , 0.35684142, 0.46774779],
        [0.57019745, 0.60634484, 0.73582465, 0.30684873, 0.50170894],
        [0.71713294, 0.4503055 , 0.30086947, 0.96958833, 0.04098392]]])

# 2. Función que muestre las propiedades de un array

In [42]:
#FUNCIÓN

def propiedades (array):
    a = ("La forma es:", array.shape)
    b = ("El tamaño es:", array.size)
    c = ("El número de dimensiones es:", array.ndim) 
    d = ("El tipo de datos es:", array.dtype)
    
    prop = a, b, c, d
    return("Las propiedades del", array, "son:", prop)

In [45]:
propiedades(array_1)
#propiedades(array_2)
#propiedades(array_3)

('Las propiedades del',
 array([[[0.60273906, 0.89757772, 0.9521491 , 0.85145229, 0.75894662],
         [0.91379953, 0.33584673, 0.93162511, 0.72580759, 0.6654558 ],
         [0.32334015, 0.89370783, 0.89043428, 0.41404964, 0.27351203]],
 
        [[0.72896408, 0.35047846, 0.7696711 , 0.35684142, 0.46774779],
         [0.57019745, 0.60634484, 0.73582465, 0.30684873, 0.50170894],
         [0.71713294, 0.4503055 , 0.30086947, 0.96958833, 0.04098392]]]),
 'son:',
 (('La forma es:', (2, 3, 5)),
  ('El tamaño es:', 30),
  ('El número de dimensiones es:', 3),
  ('El tipo de datos es:', dtype('float64'))))

# 3. Crear matriz de identidad

In [46]:
#2 dimensiones, 3 filas y 3 columnas

matriz_1 = np.identity(3)
matriz_1



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [48]:
matriz_2 = np.ones_like(matriz_1)
matriz_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 5. Operaciones

In [53]:
# 1) ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

#suma = array_2 + matriz_1
#print(array_2)
#print(matriz_1)

#No se pueden sumar, como hemos comprobado, porque tienen diferentes formas. Ambos son bidimensionales, pero el número de filas y columnas no es el mismo (2, 3) y (3, 3)



In [ ]:
# 2) En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

#opción: crear array nuevo con las mismas dimensiones: como en este caso la matriz es de tamaño 3x3, nuestro array deberá tener 3 filas y 3 columnas.

array_nuevo = 
