Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
El valor de la primera fila y la segunda columna.
Los valores de la segunda fila y las dos primeras columnas.
Extraed las filas pares (incluyendo la 0) y todas las columnas.
Extraed los valores que sean mayores que 0.5.
Extraed los valores menores que 0.2 o mayores que 0.5

In [12]:
import numpy as np
array_bidimensional= np.random.rand(5,3)
array_bidimensional

print("Esta es la fila 1, columna 2: ", array_bidimensional[0,1])
print("\n")
print("Esta es la segunda fila y 2 primeras columnas: ", array_bidimensional[1,:2])
print("\n")
print("Estas son las filas pares y todas las columnas. ", array_bidimensional[::2,:])
print("\n")
print("Estos son los valores mayores que 0.5.", array_bidimensional[array_bidimensional>0.5])
print("\n")
print("Estos son los valores menores que 0.2 o mayores que 0.5", array_bidimensional [(array_bidimensional<0.2)|(array_bidimensional>0.5)])

Esta es la fila 1, columna 2:  0.6910127928700576


Esta es la segunda fila y 2 primeras columnas:  [0.84294795 0.35356024]


Estas son las filas pares y todas las columnas.  [[0.43568415 0.69101279 0.09684587]
 [0.81501614 0.23797807 0.35044719]
 [0.54291225 0.08732191 0.07055735]]


Estos son los valores mayores que 0.5. [0.69101279 0.84294795 0.7704229  0.81501614 0.83669202 0.54872675
 0.54291225]


Estos son los valores menores que 0.2 o mayores que 0.5 [0.69101279 0.09684587 0.84294795 0.7704229  0.81501614 0.83669202
 0.54872675 0.54291225 0.08732191 0.07055735]


Cread dos array de tres dimensiones:
 El primero de 2 matrices, 5 filas y 3 columnas.
 El segundo de 3 matrices, 2 filas y 5 columnas
Haced un análisis exploratorio de los array creados

In [19]:
array_1= np.random.randint(0,100, (2,5,3))
array_2= np.random.randint(0,100, (3,2,5))

#FUNCIÓN

def propiedades (array):
    a = ("La forma es:", array.shape)
    b = ("El tamaño es:", array.size)
    c = ("El número de dimensiones es:", array.ndim) 
    d = ("El tipo de datos es:", array.dtype)
    
    print(a, "\n", b, "\n", c, "\n", d)
print("Análisis exploratorio Primer Array")
propiedades(array_1)
print("\n")
print("Análisis exploratorio Segundo Array")
propiedades(array_2)

Análisis exploratorio Primer Array
('La forma es:', (2, 5, 3)) 
 ('El tamaño es:', 30) 
 ('El número de dimensiones es:', 3) 
 ('El tipo de datos es:', dtype('int64'))


Análisis exploratorio Segundo Array
('La forma es:', (3, 2, 5)) 
 ('El tamaño es:', 30) 
 ('El número de dimensiones es:', 3) 
 ('El tipo de datos es:', dtype('int64'))


In [21]:
#Sumad los dos arrays. ¿Podéis? ¿Por qué?
#Suma= array_1+ array_2
#No se pueden sumar estos dos arrays puesto que tienen formas distintas.

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

Utiliza las funciones .reshape().transpose() para cambiar la forma de los array y hacer operaciones entre ellos

In [32]:
#transformar con transpose() para poder sumar
array_2_transpuesto= np.transpose(array_2,(1,2,0))
array_2_transpuesto

suma_a= array_2_transpuesto + array_1
suma_a

array([[[ 72,  67, 132],
        [ 79,  59,  83],
        [147,  97, 101],
        [168, 105,  85],
        [ 54, 102, 101]],

       [[147,  53,  52],
        [ 69, 100, 103],
        [131,  96,  35],
        [ 63, 160, 104],
        [ 56, 151,  87]]])

In [31]:
#transformar con reshape() para poder sumar
array_2_reshaped= array_2.reshape((2,5,3))
array_2_reshaped

sumar_b= array_1 + array_2_reshaped
sumar_b

array([[[ 72,  46, 118],
        [113,  54,  74],
        [ 89,  98,  83],
        [135, 147,  78],
        [113,  68,  67]],

       [[122,  60,  91],
        [109, 118, 111],
        [136,  96,  43],
        [118, 106, 172],
        [ 22, 113,  87]]])