Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed

# 20/04 - Pair Programming Numpy 3 - Tatiana & Lara

In [8]:
import numpy as np

array_1 = np.round(np.random.rand(2, 3, 5), decimals = 1)
array_1

array([[[0.4, 0.2, 0.2, 0.8, 0.2],
        [0.1, 0.2, 0.5, 0.2, 0.9],
        [0.8, 0.9, 0.9, 0.2, 0.8]],

       [[0.5, 0.1, 0.6, 0.6, 0.3],
        [0.9, 0.9, 0.4, 0.9, 0.8],
        [0.4, 1. , 0.9, 0.4, 0.1]]])

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
media = np.round(np.mean(array_1), decimals = 1)
media 

0.6

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [10]:
maximo = np.round(np.max(array_1), decimals = 1)
maximo

1.0

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [11]:
minimo = np.round(np.min(array_1), decimals = 1)
minimo

0.1

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

In [12]:
array_2 = np.empty_like(array_1)
array_2

array([[[0.4, 0.2, 0.2, 0.8, 0.2],
        [0.1, 0.2, 0.5, 0.2, 0.9],
        [0.8, 0.9, 0.9, 0.2, 0.8]],

       [[0.5, 0.1, 0.6, 0.6, 0.3],
        [0.9, 0.9, 0.4, 0.9, 0.8],
        [0.4, 1. , 0.9, 0.4, 0.1]]])

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

In [25]:
for elemento_uno in np.nditer(array_1):
    if elemento_uno == media:
        
        replace()
array_1

array([[[0.4, 0.2, 0.2, 0.8, 0.2],
        [0.1, 0.2, 0.5, 0.2, 0.9],
        [0.8, 0.9, 0.9, 0.2, 0.8]],

       [[0.5, 0.1, 0.6, 0.6, 0.3],
        [0.9, 0.9, 0.4, 0.9, 0.8],
        [0.4, 1. , 0.9, 0.4, 0.1]]])

In [ ]:
i=0
j=0
k=0
array_2[i][j][k]
array_1[i][j][k]
while 


In [24]:
for elemento_uno in np.nditer(array_1):
    #for elemento in np.nditer(array_1):
    if elemento_uno == media:
        elemento_uno == "A"
    #if elemento_uno > media:
        elemento_uno = "B"
    #if elemento_uno < media:
        elemento_uno = "C"
    if elemento_uno == maximo:
        elemento_uno = "D"
    if elemento_uno == minimo: 
        elemento_uno = "E" 
array_1

array([[[0.4, 0.2, 0.2, 0.8, 0.2],
        [0.1, 0.2, 0.5, 0.2, 0.9],
        [0.8, 0.9, 0.9, 0.2, 0.8]],

       [[0.5, 0.1, 0.6, 0.6, 0.3],
        [0.9, 0.9, 0.4, 0.9, 0.8],
        [0.4, 1. , 0.9, 0.4, 0.1]]])