# 21/04 - Pair Programming Numpy IV - Tatiana & Lara

¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [39]:
import numpy as np
np.random.seed(1)
array1 = np.random.random_sample((2 ,3))
print("array 1=", array1)
print('\n')
np.random.seed(1)
array2= np.random.random_sample((2, 3))
print("array 2=", array2)

array 1= [[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


array 2= [[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


Cread los siguientes arrays:
Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [40]:
array3= (np.random.uniform(0,10, size = (2,3,5))).round(0)
unicos= np.unique(array3)
print("Los valores únicos del array son=", unicos)

Los valores únicos del array son= [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable. Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [29]:
array4= np.random.binomial(10, 0.9, size = (2,3,5))
array4
print("En este caso de distribución binomial buscamos ")

array([[[ 9,  8,  9,  9,  7],
        [ 8, 10,  9,  9,  7],
        [10, 10, 10,  9, 10]],

       [[ 9,  8,  9,  8, 10],
        [ 8,  9,  8,  9, 10],
        [10, 10, 10,  9, 10]]])

Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
Elementos comunes entre los dos arrays
Unión de los dos arrays
¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [33]:
comunes = np.intersect1d(unicos, array4)
print(comunes) 
union = np.union1d(unicos,array4)
print(union)
diferentes = np.setdiff1d(unicos, array4)
print(diferentes)

[ 7.  8.  9. 10.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 1. 2. 3. 4. 5. 6.]
